
export default new Map([
["src/content/blog/14-month-wedding-planning-timeline.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2F14-month-wedding-planning-timeline.mdx&astroContentModuleFlag=true")],
["src/content/blog/18-month-wedding-planning-timeline.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2F18-month-wedding-planning-timeline.mdx&astroContentModuleFlag=true")],
["src/content/blog/20-tips-for-your-wedding-planning-checklist.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2F20-tips-for-your-wedding-planning-checklist.mdx&astroContentModuleFlag=true")],
["src/content/blog/hairstyles-for-wedding.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fhairstyles-for-wedding.mdx&astroContentModuleFlag=true")],
["src/content/blog/how-to-choose-wedding-venue.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fhow-to-choose-wedding-venue.mdx&astroContentModuleFlag=true")],
["src/content/blog/indian-wedding-hairstyles-guide.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Findian-wedding-hairstyles-guide.mdx&astroContentModuleFlag=true")],
["src/content/blog/moodboard-layout.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fmoodboard-layout.mdx&astroContentModuleFlag=true")],
["src/content/blog/pakistani-wedding-hairstyles.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fpakistani-wedding-hairstyles.mdx&astroContentModuleFlag=true")],
["src/content/blog/perfect-guest-list-guide.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fperfect-guest-list-guide.mdx&astroContentModuleFlag=true")],
["src/content/blog/regional-indian-wedding-hairstyles.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fregional-indian-wedding-hairstyles.mdx&astroContentModuleFlag=true")],
["src/content/blog/the-ultimate-wedding-planning-checklists-guide-for-a-stress-free-wedding.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fthe-ultimate-wedding-planning-checklists-guide-for-a-stress-free-wedding.mdx&astroContentModuleFlag=true")],
["src/content/blog/wedding-budget-tips.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fwedding-budget-tips.mdx&astroContentModuleFlag=true")]]);
		